### ISSUE TITLE
bugs in file7

### ISSUE THREAD

**Issue by trainingkoe** [sunnysirohi/test-gitmerge#6]
please test and modify file7

**Comment by sunnysirohi** [comment]
updated file7

**Comment by trainingkoe** [comment]
thanks

**Comment by trainingkoe** [comment]
[file7](/sunnysirohi/test-gitmerge/tree/dev/file7)

**Comment by trainingkoe** [comment]
[file7](/sunnysirohi/test-gitmerge/tree/dev/file7)
